### ISSUE TITLE
Create /roles endpoint

### ISSUE THREAD

**Issue by kaiomagalhaes** [kaiomagalhaes/team-maker-api#23]
when hitting the path:

/roles

it should return a response that matches the following:
```
[
  {
    id: 1,
    name: 'Engineer'
  }
]
```

Please make sure to create the seeds for:

`Engineer, `Engineer Leader`, `PM`, `Designer`, `Designer Lead`

**Comment by raphaelsattler** [comment]
Was created the PR #24 to solve this issue.
