### ISSUE TITLE
Create domain model

### ISSUE THREAD

**Issue by kaiomagalhaes** [kaiomagalhaes/team-maker-api#3]
We need a domain model that represents the following data:

[Engineering team workflow - Sheet1.pdf](https://github.com/kaiomagalhaes/team-maker-api/files/2624554/Engineering.team.workflow.-.Sheet1.pdf)

**Comment by raphaelsattler** [comment]
[Engineering.team.workflow.-.Sheet1.pdf](https://github.com/kaiomagalhaes/team-maker-api/files/2648498/Engineering.team.workflow.-.Sheet1.pdf)

**Comment by raphaelsattler** [comment]
![relational_diagram_engineering_team_workflow](https://user-images.githubusercontent.com/40361370/49509612-042d4700-f86d-11e8-90fb-b41d9442dcdc.jpg)
